
spring.application.name=exemplo2-spring-boot

# Define o driver do banco de dados
spring.datasource.driver-class-name=org.h2.Driver
# Define a URL de conexão do banco. 'mem' indica que é em memória e
# 'bancoteste' é o nome do banco.
spring.datasource.url=jdbc:h2:mem:bancoteste
# Define o usuário padrão para acesso.
spring.datasource.username=sa
# Define a senha vazia por padrão.
spring.datasource.password=
# Habilita o console de administração do H2 via navegador.
spring.h2.console.enabled=true
# Define a URL de acesso ao console.
spring.h2.console.path=/h2-console
# CONFIGURAÇÃO PARA O H2 FUNCIONAR NO CODESPACES
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework
# Configura o Spring Data JPA para atualizar a estrutura do banco
# automaticamente baseado nas classes Java.
spring.jpa.hibernate.ddl-auto=update
